services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: poupai-service
    depends_on:
      dynamodb-local:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      APP_URL: ${APP_URL}
      JWT_SECRET: ${JWT_SECRET}
      SMTP_EMAIL: ${SMTP_EMAIL}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/ping" ] # Adapte a URL do seu health check
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
