spring:
  application:
    name: financial-auth
    url: ${APP_URL}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
jwt:
  secret: ${JWT_SECRET}
smtp:
  email: ${SMTP_EMAIL}
  password: ${SMTP_PASSWORD}